### PR TITLE
Add support for more interfaces / multiple interfaces at once

### PR DESCRIPTION
**Pull request by simlrh**
Hello, I've added in support for different kinds of OSVR interfaces (analog, buttons, locomotion etc), as well as changed the API so you can request and save multiple different sources of information in a FreePIE script (see README and examples).

I know these are quite extensive changes so I'm happy if you just want to keep these as two separate plugins rather than maintain someone else's code.

### CODE REVIEW

**Comment by thomasgauthier** [comment]
I'm happy to merge it, this is a way more complete plugin and it provides an API more in line with the OSVR system as it is intended to be used.

**Comment by thomasgauthier** [comment]
Do you have an idea of how we could implement a write functionality, so that a FreePIE script could act as an OSVR device?

**Comment by simlrh** [comment]
I've been thinking about that this weekend. Since the running FreePIE app needs to communicate with an OSVR plugin dll, I think it needs to use memory mapped files for IPC the same way HydraSpoof.cs does in the FreePIE core plugins / Lib. But it should be dynamic rather than providing a fixed number of devices like hydra does, so maybe a named pipe which sends info from FreePIE to OSVR telling it what interfaces to look for, then OSVR can open those memory mapped files. 

I picture the FreePIE api being like

```
osvrtrackir = OSVR.device("TrackIR")
osvrtrackir.tracker[0].x = 3.0f
```

And so on, and it creates the interfaces automatically as required. Then in OSVR you'd access that data as "/com.freepie.osvr/TrackIR/tracker/0"

**Comment by thomasgauthier** [comment]
This seems like a good starting point. Let's move the conversation to https://github.com/thomasgauthier/FreePIE-OSVR/issues/5.

**Pull request merged**
